In [6]:
import pandas as pd
import numpy as np

In [7]:
ds=pd.read_csv('car.data')
ds.columns=['Buying','Maintain','Door','Per','Floor','sec','Type']
ds.head()

Buying Maintain Door Per  Floor   sec   Type
0  vhigh    vhigh    2   2  small   med  unacc
1  vhigh    vhigh    2   2  small  high  unacc
2  vhigh    vhigh    2   2    med   low  unacc
3  vhigh    vhigh    2   2    med   med  unacc
4  vhigh    vhigh    2   2    med  high  unacc

In [8]:

ds['Buying'].replace({'vhigh':1,'high':2,'med':3,'low':4},inplace=True)
ds['Maintain'].replace({'vhigh':1,'high':2,'med':3,'low':4},inplace=True)
ds["Door"].replace({"2": 1, "3": 2, "4": 3, "5more": 4}, inplace=True)
ds["Per"].replace({"2": 1, "4": 2, "more": 3}, inplace=True)
ds['Floor'].replace({'big':1,'med':2,'small':3,'more':4},inplace=True)
ds['sec'].replace({'high':1,'med':2,'low':3},inplace=True)
ds['Type'].replace({'unacc':1,'acc':2,'good':3,'vgood':4},inplace=True)
ds.head()


Buying  Maintain  Door  Per  Floor  sec  Type
0       1         1     1    1      3    2     1
1       1         1     1    1      3    1     1
2       1         1     1    1      2    3     1
3       1         1     1    1      2    2     1
4       1         1     1    1      2    1     1

In [9]:
X=ds.iloc[:,:-1].values
y=ds.iloc[:,6].values


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [11]:
from sklearn.preprocessing import StandardScaler

In [19]:
s=StandardScaler()
s.fit(X_train)
X_train=s.transform(X_train)
X_test=s.transform(X_test)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)


In [20]:
model.score(X_test,y_test)

0.9479768786127167

In [21]:
model.score(X_train,y_train)

0.9834437086092715

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.98      0.98      0.98       367
           2       0.91      0.92      0.92       119
           3       0.83      0.71      0.77        14
           4       1.00      0.84      0.91        19

    accuracy                           0.96       519
   macro avg       0.93      0.87      0.89       519
weighted avg       0.96      0.96      0.96       519

[[361   5   1   0]
 [  8 110   1   0]
 [  1   3  10   0]
 [  0   3   0  16]]
